mavros:
  ros__parameters: {}

mavros_router:
  ros__parameters: {}

mavros_node:
  ros__parameters:
    fcu_url: /dev/ttyPixhawk:921600
    gcs_url: udp://@
    

/**:
  ros__parameters:
    plugin_denylist: [odometry,distance_sensor]
    #plugin_allowlist: [ rangefinder]
